// src/constants/games.js — Base de jeux complète (500+ titres)
export const GAMES = [
  // ─── FPS ────────────────────────────────────────────────────────────────────
  { id: '1',   name: 'Call of Duty: Warzone',         genre: 'fps' },
  { id: '2',   name: 'Call of Duty: Black Ops 6',     genre: 'fps' },
  { id: '3',   name: 'Call of Duty: Modern Warfare III', genre: 'fps' },
  { id: '4',   name: 'Valorant',                      genre: 'fps' },
  { id: '5',   name: 'Counter-Strike 2',              genre: 'fps' },
  { id: '6',   name: 'Apex Legends',                  genre: 'fps' },
  { id: '7',   name: 'Overwatch 2',                   genre: 'fps' },
  { id: '8',   name: 'Rainbow Six Siege',             genre: 'fps' },
  { id: '9',   name: 'Halo Infinite',                 genre: 'fps' },
  { id: '10',  name: 'Battlefield 2042',              genre: 'fps' },
  { id: '11',  name: 'Titanfall 2',                   genre: 'fps' },
  { id: '12',  name: 'Destiny 2',                     genre: 'fps' },
  { id: '13',  name: 'Escape from Tarkov',            genre: 'fps' },
  { id: '14',  name: 'Hunt: Showdown',                genre: 'fps' },
  { id: '15',  name: 'Deep Rock Galactic',            genre: 'fps' },
  { id: '16',  name: 'Splitgate 2',                   genre: 'fps' },
  { id: '17',  name: 'FragPunk',                      genre: 'fps' },
  { id: '18',  name: 'Marathon',                      genre: 'fps' },
  { id: '19',  name: 'STALKER 2',                     genre: 'fps' },
  { id: '20',  name: 'Killing Floor 3',               genre: 'fps' },
  { id: '21',  name: '007: First Light',              genre: 'fps' },
  { id: '22',  name: 'Atomfall',                      genre: 'fps' },
  { id: '23',  name: 'Judas',                         genre: 'fps' },
  { id: '24',  name: 'Insurgency: Sandstorm',         genre: 'fps' },
  { id: '25',  name: 'Hell Let Loose',                genre: 'fps' },
  { id: '26',  name: 'Squad',                         genre: 'fps' },
  { id: '27',  name: 'Doom Eternal',                  genre: 'fps' },
  { id: '28',  name: 'Doom: The Dark Ages',           genre: 'fps' },
  { id: '29',  name: 'Quake Champions',               genre: 'fps' },
  { id: '30',  name: 'Team Fortress 2',               genre: 'fps' },

  // ─── BATTLE ROYALE ──────────────────────────────────────────────────────────
  { id: '31',  name: 'Fortnite',                      genre: 'battle_royale' },
  { id: '32',  name: 'PUBG: Battlegrounds',           genre: 'battle_royale' },
  { id: '33',  name: 'Warzone Mobile',                genre: 'battle_royale' },
  { id: '34',  name: 'Free Fire',                     genre: 'battle_royale' },
  { id: '35',  name: 'Free Fire MAX',                 genre: 'battle_royale' },
  { id: '36',  name: 'PUBG Mobile',                   genre: 'battle_royale' },
  { id: '37',  name: 'Naraka: Bladepoint',            genre: 'battle_royale' },
  { id: '38',  name: 'Super People',                  genre: 'battle_royale' },
  { id: '39',  name: 'Spellbreak',                    genre: 'battle_royale' },
  { id: '40',  name: 'Hyper Scape',                   genre: 'battle_royale' },

  // ─── RPG ────────────────────────────────────────────────────────────────────
  { id: '41',  name: 'Elden Ring',                    genre: 'rpg' },
  { id: '42',  name: 'Elden Ring: Shadow of the Erdtree', genre: 'rpg' },
  { id: '43',  name: 'The Witcher 3',                 genre: 'rpg' },
  { id: '44',  name: 'Cyberpunk 2077',                genre: 'rpg' },
  { id: '45',  name: 'Baldur\'s Gate 3',              genre: 'rpg' },
  { id: '46',  name: 'Dark Souls III',                genre: 'rpg' },
  { id: '47',  name: 'Bloodborne',                    genre: 'rpg' },
  { id: '48',  name: 'Sekiro: Shadows Die Twice',     genre: 'rpg' },
  { id: '49',  name: 'Final Fantasy XVI',             genre: 'rpg' },
  { id: '50',  name: 'Final Fantasy XIV',             genre: 'rpg' },
  { id: '51',  name: 'Final Fantasy VII Rebirth',     genre: 'rpg' },
  { id: '52',  name: 'Dragon Age: The Veilguard',     genre: 'rpg' },
  { id: '53',  name: 'Monster Hunter: World',         genre: 'rpg' },
  { id: '54',  name: 'Monster Hunter Wilds',          genre: 'rpg' },
  { id: '55',  name: 'Diablo IV',                     genre: 'rpg' },
  { id: '56',  name: 'Path of Exile 2',               genre: 'rpg' },
  { id: '57',  name: 'Genshin Impact',                genre: 'rpg' },
  { id: '58',  name: 'Honkai: Star Rail',             genre: 'rpg' },
  { id: '59',  name: 'Wuthering Waves',               genre: 'rpg' },
  { id: '60',  name: 'Black Desert Online',           genre: 'rpg' },
  { id: '61',  name: 'Lost Ark',                      genre: 'rpg' },
  { id: '62',  name: 'World of Warcraft',             genre: 'rpg' },
  { id: '63',  name: 'Elder Scrolls Online',          genre: 'rpg' },
  { id: '64',  name: 'Elder Scrolls 6',              genre: 'rpg' },
  { id: '65',  name: 'Fallout 76',                    genre: 'rpg' },
  { id: '66',  name: 'Fallout 4',                     genre: 'rpg' },
  { id: '67',  name: 'Starfield',                     genre: 'rpg' },
  { id: '68',  name: 'Dragon\'s Dogma 2',             genre: 'rpg' },
  { id: '69',  name: 'Lies of P',                     genre: 'rpg' },
  { id: '70',  name: 'Remnant II',                    genre: 'rpg' },
  { id: '71',  name: 'Nioh 2',                        genre: 'rpg' },
  { id: '72',  name: 'Code Vein',                     genre: 'rpg' },
  { id: '73',  name: 'Persona 5 Royal',               genre: 'rpg' },
  { id: '74',  name: 'Persona 3 Reload',              genre: 'rpg' },
  { id: '75',  name: 'Like a Dragon: Ishin!',         genre: 'rpg' },
  { id: '76',  name: 'Like a Dragon: Infinite Wealth', genre: 'rpg' },
  { id: '77',  name: 'Octopath Traveler II',          genre: 'rpg' },
  { id: '78',  name: 'Tales of Arise',                genre: 'rpg' },
  { id: '79',  name: 'Star Wars: Knights of the Old Republic', genre: 'rpg' },
  { id: '80',  name: 'Xenoblade Chronicles 3',        genre: 'rpg' },

  // ─── ACTION ─────────────────────────────────────────────────────────────────
  { id: '81',  name: 'God of War: Ragnarok',          genre: 'action' },
  { id: '82',  name: 'God of War (2018)',              genre: 'action' },
  { id: '83',  name: 'Spider-Man 2',                  genre: 'action' },
  { id: '84',  name: 'Spider-Man: Miles Morales',     genre: 'action' },
  { id: '85',  name: 'Batman: Arkham Knight',         genre: 'action' },
  { id: '86',  name: 'Devil May Cry 5',               genre: 'action' },
  { id: '87',  name: 'Bayonetta 3',                   genre: 'action' },
  { id: '88',  name: 'Metal Gear Solid V',            genre: 'action' },
  { id: '89',  name: 'Metal Gear Solid Delta',        genre: 'action' },
  { id: '90',  name: 'Stellar Blade',                 genre: 'action' },
  { id: '91',  name: 'Returnal',                      genre: 'action' },
  { id: '92',  name: 'Ghostrunner 2',                 genre: 'action' },
  { id: '93',  name: 'Sifu',                          genre: 'action' },
  { id: '94',  name: 'Hi-Fi Rush',                    genre: 'action' },
  { id: '95',  name: 'Assassin\'s Creed Shadows',     genre: 'action' },
  { id: '96',  name: 'Assassin\'s Creed Mirage',      genre: 'action' },
  { id: '97',  name: 'Assassin\'s Creed Valhalla',    genre: 'action' },
  { id: '98',  name: 'Marvel\'s Wolverine',           genre: 'action' },
  { id: '99',  name: 'Indiana Jones and the Great Circle', genre: 'action' },
  { id: '100', name: 'Prince of Persia: The Lost Crown', genre: 'action' },
  { id: '101', name: 'Wo Long: Fallen Dynasty',       genre: 'action' },
  { id: '102', name: 'Wanted: Dead',                  genre: 'action' },
  { id: '103', name: 'Forspoken',                     genre: 'action' },
  { id: '104', name: 'Kena: Bridge of Spirits',       genre: 'action' },
  { id: '105', name: 'Neon White',                    genre: 'action' },

  // ─── ADVENTURE ──────────────────────────────────────────────────────────────
  { id: '106', name: 'The Legend of Zelda: Tears of the Kingdom', genre: 'adventure' },
  { id: '107', name: 'The Legend of Zelda: Breath of the Wild',   genre: 'adventure' },
  { id: '108', name: 'The Legend of Zelda: Echoes of Wisdom',     genre: 'adventure' },
  { id: '109', name: 'Ghost of Tsushima',             genre: 'adventure' },
  { id: '110', name: 'Ghost of Yotei',                genre: 'adventure' },
  { id: '111', name: 'Horizon Forbidden West',        genre: 'adventure' },
  { id: '112', name: 'Horizon Zero Dawn',             genre: 'adventure' },
  { id: '113', name: 'Death Stranding 2',             genre: 'adventure' },
  { id: '114', name: 'Death Stranding',               genre: 'adventure' },
  { id: '115', name: 'The Last of Us Part I',         genre: 'adventure' },
  { id: '116', name: 'The Last of Us Part II',        genre: 'adventure' },
  { id: '117', name: 'Uncharted 4',                   genre: 'adventure' },
  { id: '118', name: 'Red Dead Redemption 2',         genre: 'adventure' },
  { id: '119', name: 'Grand Theft Auto VI',           genre: 'adventure' },
  { id: '120', name: 'Grand Theft Auto V',            genre: 'adventure' },
  { id: '121', name: 'Hogwarts Legacy',               genre: 'adventure' },
  { id: '122', name: 'Alan Wake 2',                   genre: 'adventure' },
  { id: '123', name: 'Control',                       genre: 'adventure' },
  { id: '124', name: 'A Plague Tale: Requiem',        genre: 'adventure' },
  { id: '125', name: 'Stray',                         genre: 'adventure' },
  { id: '126', name: 'Hollow Knight',                 genre: 'adventure' },
  { id: '127', name: 'Hollow Knight: Silksong',       genre: 'adventure' },
  { id: '128', name: 'Ori and the Will of the Wisps', genre: 'adventure' },
  { id: '129', name: 'It Takes Two',                  genre: 'adventure' },
  { id: '130', name: 'Disco Elysium',                 genre: 'adventure' },
  { id: '131', name: 'Outer Wilds',                   genre: 'adventure' },
  { id: '132', name: 'The Forgotten City',            genre: 'adventure' },
  { id: '133', name: 'Subnautica',                    genre: 'adventure' },
  { id: '134', name: 'Spiritfarer',                   genre: 'adventure' },
  { id: '135', name: 'Dune Awakening',                genre: 'adventure' },
  { id: '136', name: 'Silent Hill f',                 genre: 'adventure' },
  { id: '137', name: 'Silent Hill 2 Remake',          genre: 'adventure' },
  { id: '138', name: 'Resident Evil 4 Remake',        genre: 'adventure' },
  { id: '139', name: 'Resident Evil Village',         genre: 'adventure' },
  { id: '140', name: 'Intergalactic',                 genre: 'adventure' },

  // ─── SPORTS ─────────────────────────────────────────────────────────────────
  { id: '141', name: 'EA Sports FC 25',               genre: 'sports' },
  { id: '142', name: 'EA Sports FC 24',               genre: 'sports' },
  { id: '143', name: 'NBA 2K25',                      genre: 'sports' },
  { id: '144', name: 'NBA 2K24',                      genre: 'sports' },
  { id: '145', name: 'NBA 2K23',                      genre: 'sports' },
  { id: '146', name: 'Madden NFL 25',                 genre: 'sports' },
  { id: '147', name: 'Madden NFL 24',                 genre: 'sports' },
  { id: '148', name: 'MLB The Show 24',               genre: 'sports' },
  { id: '149', name: 'NHL 25',                        genre: 'sports' },
  { id: '150', name: 'PGA Tour 2K25',                 genre: 'sports' },
  { id: '151', name: 'WWE 2K24',                      genre: 'sports' },
  { id: '152', name: 'UFC 5',                         genre: 'sports' },
  { id: '153', name: 'EA Sports WRC',                 genre: 'sports' },
  { id: '154', name: 'Rocket League',                 genre: 'sports' },
  { id: '155', name: 'eFootball 2025',                genre: 'sports' },
  { id: '156', name: 'Tony Hawk\'s Pro Skater 1+2',   genre: 'sports' },
  { id: '157', name: 'EA Sports College Football 25', genre: 'sports' },
  { id: '158', name: 'TopSpin 2K25',                  genre: 'sports' },
  { id: '159', name: 'Riders Republic',               genre: 'sports' },
  { id: '160', name: 'Steep',                         genre: 'sports' },
  { id: '161', name: 'Olympic Games Tokyo 2020',      genre: 'sports' },
  { id: '162', name: 'Football Manager 2024',         genre: 'sports' },

  // ─── RACING ─────────────────────────────────────────────────────────────────
  { id: '163', name: 'Forza Horizon 5',               genre: 'racing' },
  { id: '164', name: 'Forza Motorsport',              genre: 'racing' },
  { id: '165', name: 'Gran Turismo 7',                genre: 'racing' },
  { id: '166', name: 'F1 24',                         genre: 'racing' },
  { id: '167', name: 'F1 23',                         genre: 'racing' },
  { id: '168', name: 'Need for Speed: Unbound',       genre: 'racing' },
  { id: '169', name: 'The Crew Motorfest',            genre: 'racing' },
  { id: '170', name: 'DiRT Rally 2.0',                genre: 'racing' },
  { id: '171', name: 'Assetto Corsa Competizione',    genre: 'racing' },
  { id: '172', name: 'iRacing',                       genre: 'racing' },
  { id: '173', name: 'Wreckfest 2',                   genre: 'racing' },
  { id: '174', name: 'Mario Kart 8 Deluxe',           genre: 'racing' },
  { id: '175', name: 'Mario Kart World',              genre: 'racing' },
  { id: '176', name: 'Crash Team Rumble',             genre: 'racing' },
  { id: '177', name: 'Hot Wheels Unleashed 2',        genre: 'racing' },
  { id: '178', name: 'GRID Legends',                  genre: 'racing' },
  { id: '179', name: 'RIDE 5',                        genre: 'racing' },
  { id: '180', name: 'MotoGP 24',                     genre: 'racing' },

  // ─── MOBA ───────────────────────────────────────────────────────────────────
  { id: '181', name: 'League of Legends',             genre: 'moba' },
  { id: '182', name: 'Dota 2',                        genre: 'moba' },
  { id: '183', name: 'Honor of Kings',                genre: 'moba' },
  { id: '184', name: 'Mobile Legends: Bang Bang',     genre: 'moba' },
  { id: '185', name: 'Smite 2',                       genre: 'moba' },
  { id: '186', name: 'Heroes of the Storm',           genre: 'moba' },
  { id: '187', name: 'Pokémon Unite',                 genre: 'moba' },
  { id: '188', name: 'Wild Rift',                     genre: 'moba' },
  { id: '189', name: 'Vainglory',                     genre: 'moba' },
  { id: '190', name: 'Predecessor',                   genre: 'moba' },

  // ─── FIGHTING ───────────────────────────────────────────────────────────────
  { id: '191', name: 'Street Fighter 6',              genre: 'fighting' },
  { id: '192', name: 'Mortal Kombat 1',               genre: 'fighting' },
  { id: '193', name: 'Tekken 8',                      genre: 'fighting' },
  { id: '194', name: 'Dragon Ball FighterZ',          genre: 'fighting' },
  { id: '195', name: 'Dragon Ball: Sparking! Zero',   genre: 'fighting' },
  { id: '196', name: 'Guilty Gear Strive',            genre: 'fighting' },
  { id: '197', name: 'MultiVersus',                   genre: 'fighting' },
  { id: '198', name: 'Super Smash Bros. Ultimate',    genre: 'fighting' },
  { id: '199', name: 'Granblue Fantasy Versus: Rising', genre: 'fighting' },
  { id: '200', name: 'The King of Fighters XV',       genre: 'fighting' },
  { id: '201', name: 'Injustice 2',                   genre: 'fighting' },
  { id: '202', name: 'Nickelodeon All-Star Brawl 2',  genre: 'fighting' },
  { id: '203', name: 'Them\'s Fightin\' Herds',       genre: 'fighting' },
  { id: '204', name: 'Soul Calibur VI',               genre: 'fighting' },
  { id: '205', name: 'Marvel vs. Capcom: Infinite',   genre: 'fighting' },

  // ─── STRATEGY ───────────────────────────────────────────────────────────────
  { id: '206', name: 'Age of Empires IV',             genre: 'strategy' },
  { id: '207', name: 'StarCraft II',                  genre: 'strategy' },
  { id: '208', name: 'Civilization VII',              genre: 'strategy' },
  { id: '209', name: 'Civilization VI',               genre: 'strategy' },
  { id: '210', name: 'Total War: Warhammer III',      genre: 'strategy' },
  { id: '211', name: 'Crusader Kings III',            genre: 'strategy' },
  { id: '212', name: 'Victoria 3',                    genre: 'strategy' },
  { id: '213', name: 'Hearts of Iron IV',             genre: 'strategy' },
  { id: '214', name: 'XCOM 2',                        genre: 'strategy' },
  { id: '215', name: 'Into the Breach',               genre: 'strategy' },
  { id: '216', name: 'Slay the Spire',                genre: 'strategy' },
  { id: '217', name: 'Hades',                         genre: 'strategy' },
  { id: '218', name: 'Hades II',                      genre: 'strategy' },
  { id: '219', name: 'Teamfight Tactics',             genre: 'strategy' },
  { id: '220', name: 'Hearthstone',                   genre: 'strategy' },
  { id: '221', name: 'Magic: The Gathering Arena',    genre: 'strategy' },
  { id: '222', name: 'Gwent',                         genre: 'strategy' },
  { id: '223', name: 'Clash Royale',                  genre: 'strategy' },
  { id: '224', name: 'Clash of Clans',                genre: 'strategy' },
  { id: '225', name: 'Brawl Stars',                   genre: 'strategy' },
  { id: '226', name: 'Rise of Kingdoms',              genre: 'strategy' },
  { id: '227', name: 'State of Survival',             genre: 'strategy' },
  { id: '228', name: 'Last Shelter: Survival',        genre: 'strategy' },

  // ─── SIMULATION ─────────────────────────────────────────────────────────────
  { id: '229', name: 'Microsoft Flight Simulator 2024', genre: 'simulation' },
  { id: '230', name: 'Cities: Skylines II',           genre: 'simulation' },
  { id: '231', name: 'The Sims 4',                    genre: 'simulation' },
  { id: '232', name: 'Stardew Valley',                genre: 'simulation' },
  { id: '233', name: 'Animal Crossing: New Horizons', genre: 'simulation' },
  { id: '234', name: 'Planet Zoo',                    genre: 'simulation' },
  { id: '235', name: 'Planet Coaster 2',              genre: 'simulation' },
  { id: '236', name: 'Two Point Campus',              genre: 'simulation' },
  { id: '237', name: 'Euro Truck Simulator 2',        genre: 'simulation' },
  { id: '238', name: 'American Truck Simulator',      genre: 'simulation' },
  { id: '239', name: 'Farming Simulator 25',          genre: 'simulation' },
  { id: '240', name: 'PowerWash Simulator',           genre: 'simulation' },
  { id: '241', name: 'Unpacking',                     genre: 'simulation' },
  { id: '242', name: 'House Flipper 2',               genre: 'simulation' },
  { id: '243', name: 'Coral Island',                  genre: 'simulation' },
  { id: '244', name: 'Disney Dreamlight Valley',      genre: 'simulation' },

  // ─── POKÉMON ────────────────────────────────────────────────────────────────
  { id: '245', name: 'Pokémon Scarlet',               genre: 'rpg' },
  { id: '246', name: 'Pokémon Violet',                genre: 'rpg' },
  { id: '247', name: 'Pokémon Legends: Arceus',       genre: 'rpg' },
  { id: '248', name: 'Pokémon Legends: Z-A',          genre: 'rpg' },
  { id: '249', name: 'Pokémon Sword',                 genre: 'rpg' },
  { id: '250', name: 'Pokémon Shield',                genre: 'rpg' },
  { id: '251', name: 'Pokémon GO',                    genre: 'rpg' },
  { id: '252', name: 'Pokémon Masters EX',            genre: 'rpg' },
  { id: '253', name: 'Pokémon Café ReMix',            genre: 'simulation' },
  { id: '254', name: 'New Pokémon Snap',              genre: 'simulation' },
  { id: '255', name: 'Pokémon BDSP',                  genre: 'rpg' },

  // ─── MARIO ──────────────────────────────────────────────────────────────────
  { id: '256', name: 'Super Mario Bros. Wonder',      genre: 'other' },
  { id: '257', name: 'Super Mario Odyssey',           genre: 'other' },
  { id: '258', name: 'Super Mario RPG',               genre: 'rpg' },
  { id: '259', name: 'Super Mario Party Jamboree',    genre: 'other' },
  { id: '260', name: 'Luigi\'s Mansion 3',            genre: 'other' },
  { id: '261', name: 'Donkey Kong Country Returns HD', genre: 'other' },
  { id: '262', name: 'Donkey Kong Bananza',           genre: 'other' },
  { id: '263', name: 'Paper Mario: The Thousand-Year Door', genre: 'rpg' },
  { id: '264', name: 'Metroid Prime 4',               genre: 'action' },
  { id: '265', name: 'Kirby and the Forgotten Land',  genre: 'other' },
  { id: '266', name: 'Kirby\'s Return to Dream Land Deluxe', genre: 'other' },
  { id: '267', name: 'Splatoon 3',                    genre: 'fps' },
  { id: '268', name: 'Fire Emblem Engage',            genre: 'strategy' },
  { id: '269', name: 'Pikmin 4',                      genre: 'strategy' },
  { id: '270', name: 'Star Fox Zero',                 genre: 'other' },

  // ─── MINECRAFT & SANDBOX ────────────────────────────────────────────────────
  { id: '271', name: 'Minecraft',                     genre: 'other' },
  { id: '272', name: 'Minecraft Legends',             genre: 'strategy' },
  { id: '273', name: 'Minecraft Dungeons',            genre: 'rpg' },
  { id: '274', name: 'Roblox',                        genre: 'other' },
  { id: '275', name: 'Terraria',                      genre: 'other' },
  { id: '276', name: 'Core Keeper',                   genre: 'other' },
  { id: '277', name: 'Valheim',                       genre: 'other' },
  { id: '278', name: 'Rust',                          genre: 'other' },
  { id: '279', name: 'ARK: Survival Ascended',        genre: 'other' },
  { id: '280', name: 'Palworld',                      genre: 'other' },
  { id: '281', name: 'Satisfactory',                  genre: 'simulation' },
  { id: '282', name: 'Factorio',                      genre: 'strategy' },
  { id: '283', name: 'Subnautica: Below Zero',        genre: 'adventure' },
  { id: '284', name: 'The Forest',                    genre: 'other' },
  { id: '285', name: 'Sons of the Forest',            genre: 'other' },
  { id: '286', name: 'Green Hell',                    genre: 'other' },
  { id: '287', name: 'Smalland: Survive the Wilds',   genre: 'other' },
  { id: '288', name: 'No Man\'s Sky',                 genre: 'other' },

  // ─── MOBILE (TOP MONDIAUX) ──────────────────────────────────────────────────
  { id: '289', name: 'BGMI',                          genre: 'battle_royale' },
  { id: '290', name: 'Stumble Guys',                  genre: 'other' },
  { id: '291', name: 'Among Us',                      genre: 'other' },
  { id: '292', name: 'Candy Crush Saga',              genre: 'other' },
  { id: '293', name: 'Subway Surfers',                genre: 'other' },
  { id: '294', name: 'Temple Run 2',                  genre: 'other' },
  { id: '295', name: 'Hill Climb Racing 2',           genre: 'racing' },
  { id: '296', name: 'Real Racing 3',                 genre: 'racing' },
  { id: '297', name: 'Asphalt 9: Legends',            genre: 'racing' },
  { id: '298', name: 'Arena of Valor',                genre: 'moba' },
  { id: '299', name: 'AFK Arena',                     genre: 'rpg' },
  { id: '300', name: 'Raid: Shadow Legends',          genre: 'rpg' },
  { id: '301', name: 'Summoners War',                 genre: 'rpg' },
  { id: '302', name: 'Seven Deadly Sins: Grand Cross', genre: 'rpg' },
  { id: '303', name: 'Garena AOV',                    genre: 'moba' },
  { id: '304', name: 'Magic Chess: Bang Bang',        genre: 'strategy' },
  { id: '305', name: 'PUBG: New State',               genre: 'battle_royale' },
  { id: '306', name: 'Zooba',                         genre: 'battle_royale' },
  { id: '307', name: 'Battlelands Royale',            genre: 'battle_royale' },
  { id: '308', name: 'Shadowgun Legends',             genre: 'fps' },
  { id: '309', name: 'Critical Ops',                  genre: 'fps' },
  { id: '310', name: 'Modern Combat 5',               genre: 'fps' },
  { id: '311', name: 'Dead Trigger 2',                genre: 'fps' },
  { id: '312', name: 'Alto\'s Odyssey',               genre: 'other' },
  { id: '313', name: 'Sky: Children of the Light',    genre: 'other' },
  { id: '314', name: 'Pokémon TCG Pocket',            genre: 'strategy' },
  { id: '315', name: 'Legends of Runeterra',          genre: 'strategy' },
  { id: '316', name: 'Marvel Snap',                   genre: 'strategy' },
  { id: '317', name: 'Coin Master',                   genre: 'other' },
  { id: '318', name: 'Gardenscapes',                  genre: 'other' },
  { id: '319', name: 'Homescapes',                    genre: 'other' },
  { id: '320', name: 'Royal Match',                   genre: 'other' },
  { id: '321', name: 'Monopoly GO',                   genre: 'other' },
  { id: '322', name: 'Wordle',                        genre: 'other' },
  { id: '323', name: '8 Ball Pool',                   genre: 'sports' },
  { id: '324', name: 'Mini Golf King',                genre: 'sports' },
  { id: '325', name: 'FIFA Mobile',                   genre: 'sports' },
  { id: '326', name: 'NBA Live Mobile',               genre: 'sports' },
  { id: '327', name: 'NFL Clash',                     genre: 'sports' },
  { id: '328', name: 'Dream League Soccer 2024',      genre: 'sports' },
  { id: '329', name: 'eFootball Mobile',              genre: 'sports' },
  { id: '330', name: 'Score! Hero 3',                 genre: 'sports' },

  // ─── INDIE / AUTRES ─────────────────────────────────────────────────────────
  { id: '331', name: 'Celeste',                       genre: 'other' },
  { id: '332', name: 'Cuphead',                       genre: 'other' },
  { id: '333', name: 'Shovel Knight',                 genre: 'other' },
  { id: '334', name: 'Undertale',                     genre: 'rpg' },
  { id: '335', name: 'Deltarune',                     genre: 'rpg' },
  { id: '336', name: 'Omori',                         genre: 'rpg' },
  { id: '337', name: 'Katana ZERO',                   genre: 'action' },
  { id: '338', name: 'Dead Cells',                    genre: 'action' },
  { id: '339', name: 'Blasphemous 2',                 genre: 'action' },
  { id: '340', name: 'Curse of the Dead Gods',        genre: 'action' },
  { id: '341', name: 'Vampire Survivors',             genre: 'other' },
  { id: '342', name: 'Brotato',                       genre: 'other' },
  { id: '343', name: 'Dave the Diver',                genre: 'other' },
  { id: '344', name: 'Chained Echoes',                genre: 'rpg' },
  { id: '345', name: 'Sea of Stars',                  genre: 'rpg' },
  { id: '346', name: 'Dredge',                        genre: 'other' },
  { id: '347', name: 'Tunic',                         genre: 'adventure' },
  { id: '348', name: 'Pentiment',                     genre: 'other' },
  { id: '349', name: 'Tinykin',                       genre: 'other' },
  { id: '350', name: 'Venba',                         genre: 'other' },
  { id: '351', name: 'Cocoon',                        genre: 'other' },
  { id: '352', name: 'Pizza Tower',                   genre: 'other' },
  { id: '353', name: 'Bomb Rush Cyberfunk',           genre: 'action' },
  { id: '354', name: 'Neon Abyss 2',                  genre: 'action' },
  { id: '355', name: 'Hoa',                           genre: 'other' },
  { id: '356', name: 'Season: A Letter to the Future', genre: 'other' },
  { id: '357', name: 'Viewfinder',                    genre: 'other' },
  { id: '358', name: 'A Short Hike',                  genre: 'other' },
  { id: '359', name: 'Webfishing',                    genre: 'simulation' },
  { id: '360', name: 'Schedule 1',                    genre: 'simulation' },

  // ─── HORROR / SURVIVAL ──────────────────────────────────────────────────────
  { id: '361', name: 'Dead by Daylight',              genre: 'other' },
  { id: '362', name: 'Phasmophobia',                  genre: 'other' },
  { id: '363', name: 'The Outlast Trials',            genre: 'other' },
  { id: '364', name: 'Five Nights at Freddy\'s: Security Breach', genre: 'other' },
  { id: '365', name: 'Lethal Company',                genre: 'other' },
  { id: '366', name: 'Content Warning',               genre: 'other' },
  { id: '367', name: 'Backrooms: Survival',           genre: 'other' },
  { id: '368', name: 'The Long Dark',                 genre: 'other' },
  { id: '369', name: 'Project Zomboid',               genre: 'other' },
  { id: '370', name: 'DayZ',                          genre: 'other' },
  { id: '371', name: 'Scum',                          genre: 'other' },

  // ─── MMO / EN LIGNE ─────────────────────────────────────────────────────────
  { id: '372', name: 'New World: Aeternum',           genre: 'rpg' },
  { id: '373', name: 'Albion Online',                 genre: 'rpg' },
  { id: '374', name: 'RuneScape',                     genre: 'rpg' },
  { id: '375', name: 'Old School RuneScape',          genre: 'rpg' },
  { id: '376', name: 'Guild Wars 2',                  genre: 'rpg' },
  { id: '377', name: 'Phantasy Star Online 2',        genre: 'rpg' },
  { id: '378', name: 'Blue Protocol',                 genre: 'rpg' },
  { id: '379', name: 'Tower of Fantasy',              genre: 'rpg' },
  { id: '380', name: 'Throne and Liberty',            genre: 'rpg' },
  { id: '381', name: 'MapleStory',                    genre: 'rpg' },

  // ─── SPORT ÉLECTRONIQUE / CARD GAME ─────────────────────────────────────────
  { id: '382', name: 'Yu-Gi-Oh! Master Duel',         genre: 'strategy' },
  { id: '383', name: 'Pokémon Trading Card Game Live', genre: 'strategy' },
  { id: '384', name: 'Shadowverse',                   genre: 'strategy' },
  { id: '385', name: 'Runeterra',                     genre: 'strategy' },
  { id: '386', name: 'Eternal Card Game',             genre: 'strategy' },
  { id: '387', name: 'Marvel Contest of Champions',   genre: 'fighting' },
  { id: '388', name: 'AFK Journey',                   genre: 'rpg' },
  { id: '389', name: 'Epic Seven',                    genre: 'rpg' },
  { id: '390', name: 'Nikke: Goddess of Victory',     genre: 'fps' },

  // ─── RÉCENTS 2024-2025 ───────────────────────────────────────────────────────
  { id: '391', name: 'Helldivers 2',                  genre: 'fps' },
  { id: '392', name: 'Balatro',                       genre: 'strategy' },
  { id: '393', name: 'Animal Well',                   genre: 'adventure' },
  { id: '394', name: 'Black Myth: Wukong',            genre: 'action' },
  { id: '395', name: 'Astro Bot',                     genre: 'other' },
  { id: '396', name: 'Metaphor: ReFantazio',          genre: 'rpg' },
  { id: '397', name: 'Indiana Jones and the Great Circle', genre: 'action' },
  { id: '398', name: 'Warhammer 40K: Space Marine 2', genre: 'action' },
  { id: '399', name: 'Tekken 8',                      genre: 'fighting' },
  { id: '400', name: 'Granblue Fantasy Relink',       genre: 'rpg' },
  { id: '401', name: 'Skull and Bones',               genre: 'other' },
  { id: '402', name: 'XDefiant',                      genre: 'fps' },
  { id: '403', name: 'The First Descendant',          genre: 'fps' },
  { id: '404', name: 'Once Human',                    genre: 'other' },
  { id: '405', name: 'Pax Dei',                       genre: 'rpg' },
  { id: '406', name: 'Tarisland',                     genre: 'rpg' },
  { id: '407', name: 'Dungeon Fighter Online',        genre: 'action' },
  { id: '408', name: 'MapleStory Worlds',             genre: 'other' },
  { id: '409', name: 'inZOI',                         genre: 'simulation' },
  { id: '410', name: 'Creatures of Ava',              genre: 'adventure' },
  { id: '411', name: 'Lost Records: Bloom & Rage',    genre: 'adventure' },
  { id: '412', name: 'South of Midnight',             genre: 'adventure' },
  { id: '413', name: 'Avowed',                        genre: 'rpg' },
  { id: '414', name: 'Kingdom Come: Deliverance II',  genre: 'rpg' },
  { id: '415', name: 'Like a Dragon: Pirate Yakuza in Hawaii', genre: 'rpg' },
  { id: '416', name: 'Phantom Blade Zero',            genre: 'action' },
  { id: '417', name: 'Project Century',               genre: 'action' },
  { id: '418', name: 'Hyper Light Breaker',           genre: 'action' },
  { id: '419', name: 'Cairn',                         genre: 'other' },
  { id: '420', name: 'Blue Prince',                   genre: 'other' },
  { id: '421', name: 'Clair Obscur: Expedition 33',   genre: 'rpg' },
  { id: '422', name: 'Den of Wolves',                 genre: 'fps' },
  { id: '423', name: 'Project 8',                     genre: 'sports' },
  { id: '424', name: 'Exoborne',                      genre: 'fps' },
  { id: '425', name: 'Off the Grid',                  genre: 'battle_royale' },
  { id: '426', name: 'Hawked',                        genre: 'fps' },
  { id: '427', name: 'The Outlast Trials',            genre: 'other' },
  { id: '428', name: 'Nightingale',                   genre: 'other' },
  { id: '429', name: 'Enshrouded',                    genre: 'other' },
  { id: '430', name: 'Manor Lords',                   genre: 'strategy' },
  { id: '431', name: 'Frostpunk 2',                   genre: 'strategy' },
  { id: '432', name: 'Songs of Conquest',             genre: 'strategy' },
  { id: '433', name: 'Age of Mythology: Retold',      genre: 'strategy' },
  { id: '434', name: 'Ara: History Untold',           genre: 'strategy' },
  { id: '435', name: 'Millennia',                     genre: 'strategy' },
  { id: '436', name: 'Solium Infernum',               genre: 'strategy' },
  { id: '437', name: 'Broken Roads',                  genre: 'rpg' },
  { id: '438', name: 'Towerborne',                    genre: 'action' },
  { id: '439', name: 'Judero',                        genre: 'other' },
  { id: '440', name: 'Botany Manor',                  genre: 'simulation' },
  { id: '441', name: 'Pacific Drive',                 genre: 'other' },
  { id: '442', name: 'Alone in the Dark',             genre: 'adventure' },
  { id: '443', name: 'Rise of the Ronin',             genre: 'action' },
  { id: '444', name: 'Stellar Blade',                 genre: 'action' },
  { id: '445', name: 'Enotria: The Last Song',        genre: 'action' },
  { id: '446', name: 'Flintlock: The Siege of Dawn',  genre: 'action' },
  { id: '447', name: 'TopSpin 2K25',                  genre: 'sports' },
  { id: '448', name: 'EA Sports FC Mobile',           genre: 'sports' },
  { id: '449', name: 'Tennis Clash',                  genre: 'sports' },
  { id: '450', name: 'Badminton Clash',               genre: 'sports' },
  { id: '451', name: 'Ultimate Golf',                 genre: 'sports' },
  { id: '452', name: 'Mini Football',                 genre: 'sports' },
  { id: '453', name: 'Retro Bowl',                    genre: 'sports' },
  { id: '454', name: 'Basketball Stars',              genre: 'sports' },
  { id: '455', name: 'Bowling King',                  genre: 'sports' },
  { id: '456', name: 'Pool Payday',                   genre: 'sports' },
  { id: '457', name: 'Golf Battle',                   genre: 'sports' },
  { id: '458', name: 'Paddle: Real Sports',           genre: 'sports' },
  { id: '459', name: 'Dragon Ball Z Dokkan Battle',   genre: 'strategy' },
  { id: '460', name: 'Dragon Ball Legends',           genre: 'fighting' },
  { id: '461', name: 'One Piece Treasure Cruise',     genre: 'rpg' },
  { id: '462', name: 'Naruto: Slugfest X',            genre: 'action' },
  { id: '463', name: 'My Hero Academia: The Strongest Hero', genre: 'action' },
  { id: '464', name: 'Bleach: Brave Souls',           genre: 'action' },
  { id: '465', name: 'Sword Art Online: Memory Defrag', genre: 'rpg' },
  { id: '466', name: 'Attack on Titan: Tactics',      genre: 'strategy' },
  { id: '467', name: 'Gintama Rumble',                genre: 'action' },
  { id: '468', name: 'Jump Force: Mugen',             genre: 'fighting' },
  { id: '469', name: 'Tower of God: New World',       genre: 'rpg' },
  { id: '470', name: 'Solo Leveling: ARISE',          genre: 'action' },
  { id: '471', name: 'Dark and Darker Mobile',        genre: 'rpg' },
  { id: '472', name: 'Diablo Immortal',               genre: 'rpg' },
  { id: '473', name: 'Night Crows',                   genre: 'rpg' },
  { id: '474', name: 'Odin: Valhalla Rising',         genre: 'rpg' },
  { id: '475', name: 'Mir4',                          genre: 'rpg' },
  { id: '476', name: 'Seven Knights 2',               genre: 'rpg' },
  { id: '477', name: 'KartRider Rush+',               genre: 'racing' },
  { id: '478', name: 'Road Rush Cars',                genre: 'racing' },
  { id: '479', name: 'CSR Racing 3',                  genre: 'racing' },
  { id: '480', name: 'Beach Buggy Racing 2',          genre: 'racing' },
  { id: '481', name: 'Traffic Rider',                 genre: 'racing' },
  { id: '482', name: 'Moto X3M',                      genre: 'racing' },
  { id: '483', name: 'Geometry Dash',                 genre: 'other' },
  { id: '484', name: 'Fall Guys',                     genre: 'other' },
  { id: '485', name: 'Gang Beasts',                   genre: 'fighting' },
  { id: '486', name: 'Human: Fall Flat',              genre: 'other' },
  { id: '487', name: 'Goat Simulator 3',              genre: 'other' },
  { id: '488', name: 'Totally Accurate Battle Simulator', genre: 'strategy' },
  { id: '489', name: 'SpongeBob SquarePants: The Cosmic Shake', genre: 'other' },
  { id: '490', name: 'Sonic Frontiers',               genre: 'action' },
  { id: '491', name: 'Sonic the Hedgehog 2',          genre: 'action' },
  { id: '492', name: 'Crash Bandicoot 4',             genre: 'other' },
  { id: '493', name: 'Ratchet & Clank: Rift Apart',   genre: 'action' },
  { id: '494', name: 'Sackboy: A Big Adventure',      genre: 'other' },
  { id: '495', name: 'Knack 2',                       genre: 'action' },
  { id: '496', name: 'Astro\'s Playroom',             genre: 'other' },
  { id: '497', name: 'Bugsnax',                       genre: 'other' },
  { id: '498', name: 'Little Big Planet 3',           genre: 'other' },
  { id: '499', name: 'Dreams',                        genre: 'other' },
  { id: '500', name: 'Teardown',                      genre: 'other' },
];

export function getGameById(id) {
  return GAMES.find(g => g.id === id);
}
